AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: chat-document-backend

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  LLMMODELID:
    Type: String
    Default: "anthropic.claude-3-sonnet-20240229-v1:0"
  KBID:
    Type: String
  DSID:
    Type: String
  BUCKET:
    Type: String

Resources:
  SyncKBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/sync_kb/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BUCKET
        - Statement:
            - Sid: BedrockPolicy
              Effect: Allow
              Action:
                - bedrock:*
              Resource: "*"
      Environment:
        Variables:
          KBID: !Ref KBID
          DSID: !Ref DSID

  UploadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/s3_presigned_upload/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BUCKET
      Environment:
        Variables:
          BUCKET: !Ref BUCKET
      Events:
        UploadDocument:
          Type: Api
          Properties:
            Path: /upload
            Method: post

  AnswerQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/answer_question/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BUCKET
        - Statement:
            - Sid: BedrockPolicy
              Effect: Allow
              Action:
                - bedrock:*
              Resource: "*"
      Environment:
        Variables:
          LLMMODELID: !Ref LLMMODELID
          KBID: !Ref KBID
      Events:
        AnswerQuestion:
          Type: Api
          Properties:
            Path: /chat
            Method: get

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/search_docs/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 15
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: BedrockPolicy
              Effect: Allow
              Action:
                - bedrock:*
              Resource: "*"
      Environment:
        Variables:
          KBID: !Ref KBID
      Events:
        SearchDocs:
          Type: Api
          Properties:
            Path: /search
            Method: get

  DownloadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/s3_presigned_download/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET: !Ref BUCKET
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BUCKET
      Events:
        S3PresignedUrl:
          Type: Api
          Properties:
            Path: /download
            Method: get

Outputs:
  BackendAPI:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
